//
// Generated file, do not edit! Created by opp_msgtool 6.1 from inet/applications/vehicular/TrafficPacket.msg.
//

#ifndef __INET_TRAFFICPACKET_M_H
#define __INET_TRAFFICPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class TrafficPacket;

}  // namespace inet

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/applications/vehicular/TrafficPacket.msg:19</tt> by opp_msgtool.
 * <pre>
 * class TrafficPacket extends FieldsChunk
 * {
 *     int appIdentifier;
 * }
 * </pre>
 */
class INET_API TrafficPacket : public ::inet::FieldsChunk
{
  protected:
    int appIdentifier = 0;

  private:
    void copy(const TrafficPacket& other);

  protected:
    bool operator==(const TrafficPacket&) = delete;

  public:
    TrafficPacket();
    TrafficPacket(const TrafficPacket& other);
    virtual ~TrafficPacket();
    TrafficPacket& operator=(const TrafficPacket& other);
    virtual TrafficPacket *dup() const override {return new TrafficPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getAppIdentifier() const;
    virtual void setAppIdentifier(int appIdentifier);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TrafficPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TrafficPacket& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::TrafficPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::TrafficPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_TRAFFICPACKET_M_H

